FROM @@BASE_IMAGE@@
ARG USER=USER
ARG UID=1000
ARG GID=1000
ARG PW=anydesk

ENV XDG_RUNTIME_DIR=/tmp
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV XLIB_SKIP_ARGB_VISUALS=1
ENV TZ=Europe/Berlin
ENV DEBIAN_FRONTEND=noninteractive

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /root

ENTRYPOINT ["/bin/bash"]